version: '2'
services:
  proxy:
    build:
      context: ./proxy
    ports:
    - 8000:8080
    depends_on:
    - gemstash
    environment:
      PROXY_TARGET_URL: "http://gemstash:9292"
      IPS_ACCESS_WHITELIST: 172.18.0.1
      BASIC_AUTH_TOKEN: abcd
  gemstash:
    build: .
    ports:
    - 9292
    depends_on:
    - mariadb
    environment:
      DB_HOST: mariadb
      DB_USER: gemstash
      DB_PASSWORD: gemstash
      DB_NAME: gemstash
  mariadb:
    image: mariadb:5.5
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_USER: gemstash
      MYSQL_PASSWORD: gemstash
      MYSQL_DATABASE: gemstash
